id = "github-theme"
name = "Github Theme"
version = "0.1.2"
schema_version = 1
authors = ["Pyae Sone Aung <pyaesoneaungrgn@gmail.com>", "Clay Tercek"]
description = "GitHub themes for Zed"
repository = "https://github.com/PyaeSoneAungRgn/github-zed-theme"
